version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - .env

  redis:
    image: redis:6.0.4
    restart: always
    ports: 
      - 6379:6379

  api:
    build:
      context: ./api
    ports: 
      - 3000:3000
    depends_on:
      - mongo
      - mongo-express
      - redis
    env_file:
      - .env
    network_mode: host
    restart: always

