version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 8080:27017
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    env_file:
      - .env

